In [14]:
import numpy as np

oned = np.array([[1,2,3,4,5,6,7,8,9]])

print(oned.tolist())


[[1, 2, 3, 4, 5, 6, 7, 8, 9]]


In [29]:
import numpy as np
tra= np.array([[1,3,4,5],[6,7,8,9],[3,5,6,7]])
tra.trace()

14

In [30]:
x = 2np.array
tra [tra>x]

array([3, 4, 5, 6, 7, 8, 9, 3, 5, 6, 7])

In [31]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[4,5,6],[7,8,9]])
array3 = array1+array2
print (array3)

[[ 5  7  9]
 [11 13 15]]


In [47]:
import numpy as np
array = np.array([[4,5,6],[7,8,9]])
print(array)
b = array - array.mean(axis=1, keepdims=True)
print(b)

[[4 5 6]
 [7 8 9]]
[[-1.  0.  1.]
 [-1.  0.  1.]]
